import { Dispatch, SetStateAction } from 'react';

export type UseState<T> = [T, Dispatch<SetStateAction<T>>];

export * from './useClick';
export * from './useInput';
export * from './usePrevProps';
export * from './useL10n';
export * from './useClickOutside';
export * from './useRole';
export * from './useContentFoundById';
export * from './useAuthHeader';
export * from './useRouteIsMatching';
export * from './useWindowSize';
export * from './useIsVolumeOutdated';
export * from './useUpdateVolume';
export * from './contents';
export * from './screens';
export * from './useEditableText';
export * from './useLastSelectedScreen';
export * from './useProjectCoordinateSystem';
export * from './useToastify';
export * from './useToastify/text';
export * from './useDidMountEffect';
export * from './useContent';
export * from './useShouldContentDisabled';
export * from './useGoToZendesk';
export * from './useEscapeMeasurement';
export * from './useExitCreatingVolume';
export * from './useConstant';
